### ISSUE TITLE
Unable to install package due to missing requirements

### ISSUE THREAD

**Issue by maciejb** [GibbsConsulting/jupyter-plotly-dash#21]
setup.py requires this package itself (import jupyter_plotly_dash), so pip is unable to read the list of requirements (django-plotly-dash, etc) in order to install them. This line should be removed.

**Comment by GibbsConsulting** [comment]
Hi @maciejb, thanks for this. This repository is a bit behind in a number of things, including information about contributors and contributing. At the moment we're only accepting contributions under a contributor's agreement - please feel free to contact me at jpd-contributor@gibbsconsulting.ca to discuss further.

**Comment by GibbsConsulting** [comment]
Dependencies should now be fixed in 0.2.0 after merge of PR #26
