### ISSUE TITLE
Could not find a version that satisfies the requirement dpd-static-components

### ISSUE THREAD

**Issue by yamacisik** [GibbsConsulting/jupyter-plotly-dash#53]
When trying pip install, there is an error message as follows: 

ERROR: Could not find a version that satisfies the requirement dpd-static-components (from jupyter-plotly-dash) (from versions: none)

Running on Python 3.7.3
[spec-file.txt](https://github.com/GibbsConsulting/jupyter-plotly-dash/files/4148838/spec-file.txt)

**Comment by tanzin29** [comment]
I am also getting the same error. is it something related to device compatibility? I am using python 3.7.4

**Comment by GibbsConsulting** [comment]
Versions 0.4.0 and 0.4.1 had bad dependencies.
This has been fixed with PR #54 and released as 0.4.2

Things should work fine now, so closing this issue. Please reopen if the problem remains.
