### ISSUE TITLE
maximize the size of the output from a cell

### ISSUE THREAD

**Issue by JefVandooren** [GibbsConsulting/jupyter-plotly-dash#55]
Currently when using jupyter-plotly-dash the output of a cell is smaller (less width) than when not using it. 
Is this an issue where the dash app does not fill the full output field of a Jupyter notebook? Or is there an easy work-around? 
this is how it looks when using jupyter-plotly-dash
![image](https://user-images.githubusercontent.com/60874935/74736430-fdf96f80-5252-11ea-81bf-08c1f996fa6c.png)

this is how it looks when dash isn't used, the graph fills the entire width of the screen.
![image](https://user-images.githubusercontent.com/60874935/74736299-b541b680-5252-11ea-8eba-98b6192b41b5.png)

**Comment by GibbsConsulting** [comment]
The output window is controlled by the `height` and `width` parameters passed to the `JupyterDash` constructor.
At the moment, the output doesn't autosize.

**Comment by JefVandooren** [comment]
Thanks!  
`app = JupyterDash("appname", width = "100%")`
indeed did the trick
